In [11]:
#********************************************************************
#                    DATE STRTED:                                   *
#                   01 November 2022 [GMT-2]                        *
#                                                                   *
#     Author: Ipfani Mutavhatsindi                                  *
#     LinkedIn: https://www.linkedin.com/in/ipfani-mutavhatsindi    *       
#     Website: https://ipfani.github.io/                            *    
#                                                                   *
#********************************************************************

# The main aim of this project is to get the PSL log data table, clean it and then use ML to predict the outcome of the next match

from bs4 import BeautifulSoup
import requests
import pandas as pd 
import urllib.parse 
import pprint

from datetime import datetime

# Returns the current local date
current_dateTime = date.today()


pp = pprint.PrettyPrinter(indent=10)

#Website PSL WEBSITE
website =requests.get('https://www.psl.co.za/matchcentre?type=log')


#My variables for storing raw data
team_names = []
team_logos = []
match_played = []
win = []
Draw = []
Lost = []
Points = []

#Lets create DataFrame with these headings
df_psl = pd.DataFrame(columns=['Name', 'Match Played', 'Win', 'Draw', 'Lost', 'Points'])

soup = BeautifulSoup(website.content, 'html.parser')

table_html = soup.find('tbody', id="LogViewContent")
## pp.pprint(table_html)

# Every team is divided in a row (tr), This gives me team data as in rows
##team_row_data = table_html.find_all('tr')
## pp.pprint(team_row_data)

#''' Output of a row from the PSL website
    # <tr>
    # <td class="logs-team">
    # <div class="team-meta">
    # <a href="/club/Mamelodi_Sundowns?league=betway-premiership">
    # <div class="team-meta__info">
    # <h5 class="team-meta__name">2   </h5>
    # </div>
    # <figure class="team-meta__logo">
    # <img alt="Mamelodi Sundowns" onerror="this.src='https://www.psl.co.za/newpsl/images/clublogos/noclublogo.png';" src="https://www.psl.co.za/newpsl/images/clublogos/Mamelodi Sundowns.png"/>
    # </figure>
    # <div class="team-meta__info">
    # <h6 class="team-meta__name">Mamelodi Sundowns</h6>
    # </div>
    # </a>
    # </div>
    # </td>
    # <td class="logs-played">6</td>
    # <td class="logs-win">5</td>
    # <td class="logs-draw">0</td>
    # <td class="logs-lost">1</td>
    # <td class="logs-goals-for">13</td>
    # <td class="logs-goals-against">4</td>
    # <td class="logs-goal-diff">9</td>
    # <td class="logs-points">15</td>
    # </tr>,
#'''

team_names = soup.find_all(class_= 'team-meta__name')
match_played = soup.find_all('td', class_='logs-played')
Win = soup.find_all('td', class_='logs-win')
Draw = soup.find_all('td', class_='logs-draw')
Lost = soup.find_all('td', class_='logs-lost')
Points = soup.find_all('td', class_='logs-points')


#OUTPUT
#******************************************************************************************************************************************** 

for row in range (16): # There are 16 teams in PSL as of November 2024
    df_psl = pd.concat([df_psl, pd.DataFrame.from_records([{'Name':team_names[row].string,
                                                            'Match Played' :match_played[row].string,
                                                            'Win':Win[row].text,
                                                            'Draw':Draw[row].string,
                                                            'Lost':Lost[row].string,
                                                            'Points':Points[row].string}])], ignore_index=True)



#******************************************************************************************************************************************** 

print("***********************************************************************")
print("Current Table Log as of ", current_dateTime)
print("***********************************************************************")
print(" ")

df_psl.info()
print(" ")

pp.pprint(df_psl)

#Write to CSV File
df_psl.to_csv('PSL-Log.csv')

***********************************************************************
Current Table Log as of  2024-11-01
***********************************************************************

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16 non-null     object
 1   Match Played  16 non-null     object
 2   Win           16 non-null     object
 3   Draw          16 non-null     object
 4   Lost          16 non-null     object
 5   Points        16 non-null     object
dtypes: object(6)
memory usage: 900.0+ bytes

                 Name Match Played Win Draw Lost Points
0     Orlando Pirates            6   6    0    0     18
1        Richards Bay            6   5    0    1     15
2     Stellenbosch FC            6   4    1    1     13
3           TS Galaxy            6   3    2    1     11
4   Mamelodi Sundowns            5   3    1    1     10
5      Polokwane City            7   3    1    3     10
6       Chippa United            7   2    2    3      8
7   SuperSport United            5   2    1    2      7
8            Royal AM            7   1    4    2      7
9       Golden Arrows            6   2    1    3      7
10  Sekhukhune United            6   1    3    2      6
11          TS Galaxy            6   1    2    3      5
12  Cape Town City FC            5   1    2    2      5
13     Polokwane City            6   1    1    4      4
14      Kaizer Chiefs            5   1    0    4      3
15       Richards Bay            5   0    1    4      1

In [12]:
#Reading the produced csv and Checking the data

df = pd.read_csv('PSL-Log.csv')
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

                Name  Match Played  Win  Draw  Lost  Points
0    Orlando Pirates             6    6     0     0      18
1       Richards Bay             6    5     0     1      15
2    Stellenbosch FC             6    4     1     1      13
3          TS Galaxy             6    3     2     1      11
4  Mamelodi Sundowns             5    3     1     1      10